encryptionsalt: v1:6/zfWfWGCmk=:v1:EabJxRYO+P9qughm:pVT3uflMRXsY9XO+IMDWSkB/SK+DQA==
config:
  aws:region: us-west-2
  aws:assumeRole:
    roleArn: arn:aws:iam::912773994842:role/BenchmarkClusterAdmin
  aws:defaultTags:
    tags:
      cluster: xxlarge-cassandra
      clusterSize: xxlarge
  temporal-otb-benchmarks-cluster:AWS:
    Region: us-west-2
    AvailabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    PrivateSubnetIds: ["subnet-00e269bfc224d9c88", "subnet-0331497242f215670", "subnet-0e19e96d60a8d43fe"]
    RdsSubnetGroupName: "temporal-benchmark-rds-d034419"
    Role: BenchmarkClusterAdmin
    VpcId: "vpc-0f0ab8c917df6d422"
    PrometheusEndpoint: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-cc07bde8-10f1-4360-99a9-a5ed8f9a0657
  temporal-otb-benchmarks-cluster:Benchmark:
    Namespaces: 12
    ConcurrentWorkflows: 5500
    Target: 30000
    Workers:
      Pods: 3
      CPU:
        Request: 0.5
      Memory:
        Request: 50Mi
      WorkflowPollers: 100
      ActivityPollers: 150
    SoakTest:
      Pods: 1
      CPU:
        Request: 0.25
      Memory:
        Request: 50Mi
  temporal-otb-benchmarks-cluster:Cluster:
    EKS:
      NodeType: r5.xlarge
      NodeCount: 3
      TemporalNodeType: c5.4xlarge
      TemporalNodeCount: 16
      WorkerNodeType: c5.xlarge
      WorkerNodeCount: 8
  temporal-otb-benchmarks-cluster:Persistence:
    Cassandra:
      NodeType: c5.2xlarge
      NodeCount: 60
      CPU:
        Limit: 8
      Memory:
        Limit: 16Gi
      CommitLogStorage: 512Mi
      DataStorage: 512Gi
    Visibility:
      OpenSearch:
        MasterInstanceType: r6gd.2xlarge.search
        MasterInstanceCount: 3
        DataInstanceType: r6gd.2xlarge.search
        DataInstanceCount: 9
        EngineVersion: OpenSearch_2.11
  temporal-otb-benchmarks-cluster:Temporal:
    Frontend:
      Pods: 15
      CPU:
        Request: 2
      Memory:
        Request: 256Mi
    History:
      Shards: 4096
      Pods: 12
      CPU:
        Request: 8
      Memory:
        Request: 8Gi
    Matching:
      Pods: 9
      CPU:
        Request: 4
      Memory:
        Request: 256Mi
    Worker:
      Pods: 2
      CPU:
        Request: 0.25
      Memory:
        Request: 128Mi
    DynamicConfig:
      FrontendRPS: 6000
      FrontendNamespaceRPS: 1000
      HistoryRPS: 5000
      MatchingRPS: 5000

