encryptionsalt: v1:6/zfWfWGCmk=:v1:EabJxRYO+P9qughm:pVT3uflMRXsY9XO+IMDWSkB/SK+DQA==
config:
  aws:region: us-west-2
  aws:assumeRole:
    roleArn: arn:aws:iam::912773994842:role/BenchmarkClusterAdmin
  aws:defaultTags:
    tags:
      cluster: small-cassandra
      clusterSize: small
  temporal-otb-benchmarks-cluster:AWS:
    Region: us-west-2
    AvailabilityZones: ["us-west-2a", "us-west-2b", "us-west-2c"]
    PrivateSubnetIds: ["subnet-00e269bfc224d9c88", "subnet-0331497242f215670", "subnet-0e19e96d60a8d43fe"]
    RdsSubnetGroupName: "temporal-benchmark-rds-d034419"
    Role: BenchmarkClusterAdmin
    VpcId: "vpc-0f0ab8c917df6d422"
    PrometheusEndpoint: https://aps-workspaces.us-west-2.amazonaws.com/workspaces/ws-cc07bde8-10f1-4360-99a9-a5ed8f9a0657
  temporal-otb-benchmarks-cluster:Benchmark:
    Namespaces: 3
    ConcurrentWorkflows: 100
    Target: 500
    Workers:
      Pods: 3
      CPU:
        Request: 1
      Memory:
        Request: 50Mi
      WorkflowPollers: 30
      ActivityPollers: 50
    SoakTest:
      Pods: 1
      CPU:
        Request: 0.25
      Memory:
        Request: 50Mi
  temporal-otb-benchmarks-cluster:Cluster:
    EKS:
      NodeType: r5.xlarge
      NodeCount: 3
      TemporalNodeType: c5.2xlarge
      TemporalNodeCount: 3
      WorkerNodeType: c5.2xlarge
      WorkerNodeCount: 3
  temporal-otb-benchmarks-cluster:Persistence:
    Cassandra:
      NodeType: c5.2xlarge
      NodeCount: 3
      CPU:
        Limit: 8
      Memory:
        Limit: 16Gi
      CommitLogStorage: 256Mi
      DataStorage: 128Gi
    Visibility:
      OpenSearch:
        MasterInstanceType: r6gd.large.search
        MasterInstanceCount: 3
        DataInstanceType: r6gd.large.search
        DataInstanceCount: 3
        EngineVersion: OpenSearch_2.11
  temporal-otb-benchmarks-cluster:Temporal:
    Frontend:
      Pods: 3
      CPU:
        Request: 1
      Memory:
        Request: 256Mi
    History:
      Shards: 512
      Pods: 3
      CPU:
        Request: 1
      Memory:
        Request: 4Gi
    Matching:
      Pods: 3
      CPU:
        Request: 1
      Memory:
        Request: 256Mi
    Worker:
      Pods: 3
      CPU:
        Request: 0.25
      Memory:
        Request: 128Mi
